#!/usr/bin/with-contenv bash

# Determine if setup is needed
if [ -f /usr/bin/apt ]; then
  ## Ubuntu
  apt-get update
  apt-get install --no-install-recommends -y \
    curl
fi
if [ -f /sbin/apk ]; then
  # Alpine
  apk add --no-cache \
    curl
fi

chown -R root:root /root
chmod -R 600 /root/.ssh
